
networks:
  my_network:
    driver: bridge

services:
  flask-app:
    build:
      context: ./src
      dockerfile: Dockerfile.app
    container_name: flask-app
    ports:
      - "8095:8095"
    depends_on:
      - memcached
    environment:
      - FLASK_ENV=development
      - OPERATING_SYSTEM=docker-compose
      - MEMCACHED_HOST=memcached
    networks:
      - my_network
    links:
      - memcached
    volumes:
      - ./src:/app  # Mount current directory for development

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      - my_network

  test-app:
    build:
      context: ./src
      dockerfile: Dockerfile.test
    container_name: flask-tests
    depends_on:
      - flask-app
    networks:
      - my_network
    volumes:
      - ./src:/app
    links:
      - flask-app
    environment:
      - TEST_TAG=${TEST_TAG:-""}
    entrypoint: ["pytest", "-m", "${TEST_TAG}", "--maxfail=5", "--disable-warnings", "/src/test_app.py"]

