
services:
  flask-app:
    image: dockerelvis/python-memcached:${VERSION}
    container_name: flask-container
    ports:
      - "8091:8095"  # Map port 8081 of the container to 8081 on the host
    depends_on:
      - memcached
    environment:
      - FLASK_ENV=development
      - OPERATING_SYSTEM=docker-compose
      - MEMCACHED_HOST=memcached
    networks:
      - my_network

  memcached:
    image: memcached:latest
    container_name: memcached-container
    ports:
      - "11211:11211"  # Map the Memcached default port
    networks:
      - my_network

networks:
  my_network:
    driver: bridge  # Default driver