#!/usr/bin/env -S ansible-playbook -K
# NOTE: Don't provide the playbook filename in the shebang. It is added automatically
---

- name: Install k3 playbook
  hosts: all
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: true

  tasks:

    ##################################
    # Updates
    ##################################
    - name: Updates
      apt:
        update_cache: yes
        cache_valid_time: 3600

    ##################################
    # Disable swap
    ##################################
    - name: Disable SWAP
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    ##################################
    # Create empty modules
    ##################################
    - name: Create an empty file for the containerd module
      copy:
        content: ""
        dest: /etc/modules-load.d/containerd.conf
        force: no

    - name: Configure modules for containerd
      blockinfile:
        path: /etc/modules-load.d/containerd.conf
        block: |
          overlay
          br_netfilter

    - name: Create an empty file for K8S sysctl parameters
      copy:
        content: ""
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        force: no

    ##################################
    # Configure systemctl
    ##################################
    - name: Configure sysctl parameters for K8S
      lineinfile:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        line: "{{ item }}"
      with_items:
        - "net.bridge.bridge-nf-call-iptables  = 1"
        - "net.ipv4.ip_forward                 = 1"
        - "net.bridge.bridge-nf-call-ip6tables = 1"

    - name: Apply sysctl parameters
      command: sysctl --system

    ##################################
    # Install Apt Transport
    ##################################
    - name: Install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present

    - name: Ensure keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    ##################################
    # Install Docker
    ##################################
    - name: Add Docker apt-key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker-apt-keyring.asc
        mode: "0644"
        force: true

    - name: Add Docker's APT repo
      apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }} signed-by=/etc/apt/keyrings/docker-apt-keyring.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes
    ##################################
    # Install Kubernetes
    ##################################

    - name: Ensure the keyrings directory exists
      become: yes
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes GPG key
      become: yes
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /tmp/kubernetes-apt-key.key

    - name: Convert GPG key to keyring format
      become: yes
      shell: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-apt-key.key
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg


    - name: Add Kubernetes apt-key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: "0644"
        force: true

    - name: Add Kubernetes apt repository
      shell: |
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Updates after repo install
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install containerd
      apt:
        name: containerd.io
        state: present

    - name: Create containerd directory
      file:
        path: /etc/containerd
        state: directory

    - name: Add containerd configuration
      shell: /usr/bin/containerd config default > /etc/containerd/config.toml

    - name: Configuring Systemd cgroup driver for containerd
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: "            SystemdCgroup = false"
        line: "            SystemdCgroup = true"

    - name: Enable the containerd service and start service
      systemd:
        name: containerd
        state: restarted
        enabled: yes
        daemon-reload: yes

    ##################################
    # Install k3
    ##################################
    - name: Install Kubelet
      apt:
        name: kubelet
        state: present
        update_cache: true

    - name: Install Kubeadm
      apt:
        name: kubeadm
        state: present

    - name: Install Kubectl
      apt:
        name: kubectl
        state: present

    - name: Enable the Kubelet service
      service:
        name: kubelet
        enabled: yes

    ##################################
    # Load br_netfilter kernel module
    ##################################
    - name: Load br_netfilter kernel module
      modprobe:
        name: br_netfilter
        state: present

    ##################################
    # Set bridge-nf-call-iptables
    ##################################
    - name: Set bridge-nf-call-iptables
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1

    ##################################
    # Set ip_forward
    ##################################
    - name: Set ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: 1

    ##################################
    # Reboot
    ##################################
    - name: Reboot
      reboot: