#!/usr/bin/env -S ansible-playbook -K
# NOTE: Don't provide the playbook filename in the shebang. It is added automatically.
---

- name: Install NFS provider playbook
  hosts: master
  remote_user: kube_user
  become: yes
  tasks:

    ##################################
    # Updates
    ##################################
    - name: Updates
      apt:
        update_cache: yes

    - name: Secure Kubernetes configuration file
      become: no
      file:
        path: /home/kube_user/.kube/config
        owner: kube_user
        group: kube_user
        mode: '0600'
      when: ansible_user == 'kube_user'

    ##################################
    # Add Helm signing key
    ##################################
    - name: Download and add Helm signing key
      ansible.builtin.shell: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        apt-get update
        apt-get install helm
    ##################################
    # Add nfs-provider
    ##################################
    - name: Add NFS Subdir External Provisioner Helm repo
      command: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      register: helm_repo_add_result
      failed_when: "'Error' in helm_repo_add_result.stderr"

    - name: Update Helm repositories
      command: helm repo update
      register: helm_repo_update_result
      failed_when: "'Error' in helm_repo_update_result.stderr"

    - name: Create storagenfs namespace if it doesn't exist
      become: no
      shell: |
        kubectl get ns storagenfs || kubectl create ns storagenfs
      ignore_errors: yes


    ##################################
    # Install nfs-provider
    ##################################
    - name: Add NFS Subdir External Provisioner Helm repository
      become: no
      shell: |
        helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
        helm repo update
      register: helm_repo_add_update
      failed_when: "'Error' in helm_repo_add_update.stderr"

    - name: Check if NFS Subdir External Provisioner is already installed
      become: no
      shell: |
        helm list -n storagenfs | grep -w "nfs-subdir-external-provisioner" || echo "not found"
      register: helm_list_result
      changed_when: false

    - name: Install NFS Subdir External Provisioner
      become: no
      shell: |
        helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
          --set nfs.server="{{ hostvars['kube_master'].ansible_host }}" \
          --set nfs.path=/k8mount \
          --set storageClass.onDelete=true -n storagenfs
      when: helm_list_result.stdout == "not found"
      register: helm_install_result
      failed_when: "'Error' in helm_install_result.stderr and 'AlreadyExists' not in helm_install_result.stderr"



    - name: Show NFS provisioner status
      debug:
        msg:
          - "Helm Install Result: {{ helm_install_result }}"
          - "Helm List Result: {{ helm_list_result }}"

