#!/usr/bin/env -S ansible-playbook -K
# NOTE: Don't provide the playbook filename in the shebang. It is added automatically.
---

- name: Initialize workers playbook
  hosts: master
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: true

  tasks:

    ##################################
    # Retrieve Join Command
    ##################################
    - name: Get Kubeadm join command
      command: kubeadm token create --print-join-command
      register: join_command

    ##################################
    # Set Join Command
    ##################################
    - name: Show Kubeadm join command
      debug:
        msg: "{{ join_command.stdout }}"
      when: join_command is defined

    - name: Store the join command for later use
      add_host:
        name: "all_workers"
        kube_join_command: "{{ join_command.stdout }}"

- name: Add workers playbook
  hosts: worker
  remote_user: ubuntu
  become: yes
  become_user: root

  tasks:
    ##################################
    # Wait for TCP port 6443 to be open
    ##################################
    - name: Wait for TCP port 6443 to be open on the master node
      wait_for:
        host: "{{ hostvars['kube_master'].ansible_host }}"
        port: 6443
        timeout: 120  # Timeout in seconds
        state: started  # Ensures the port is open and listening

    ##################################
    # Join worker to cluster
    ##################################
    - name: Execute Kubeadm join on worker nodes
      command: "{{ hostvars['all_workers']['kube_join_command'] }}"
      register: join_command_executed

    - name: Show join command execution
      debug:
        msg: "{{ join_command_executed }}"
